### ISSUE TITLE
Incorrect rayleigh_damp_table in field_table

### ISSUE THREAD

**Issue by fabiobdias** [OceansAus/1deg_core_nyf#1]
There an inconsistency between field_table in 1deg_core_nyf and 1deg_jra55v13_ryf8485 control experiments. The first includes the modifications for the Indonesia Throughflow but the second don't.

Also, there is a weird thing in field_table line 118 of 1deg_core_nyf. Looks like a path of something was added in the middle of that line.

**Comment by aidanheerdegen** [comment]
>  There an inconsistency between field_table in 1deg_core_nyf and 1deg_jra55v13_ryf8485 control experiments. The first includes the modifications for the Indonesia Throughflow but the second don't.

This is referring to the rayleigh damping terms starting here:

https://github.com/OceansAus/1deg_core_nyf/blob/master/ocean/field_table#L54

The `1deg_jra55v13_ryf8485` `diag_table` presumably looks the same as this:

https://github.com/OceansAus/1deg_jra55_ryf/blob/master/ocean/field_table

So yes, there are no Rayleigh damping terms at all. I suppose there was a desire to not use these unless necessary and get Simon's to check he was happy with the Indo through flow numbers. Has he done this? I seem to recall some mention of it a while back in a MOM meeting, but can't recall details.

> Also, there is a weird thing in field_table line 118 of 1deg_core_nyf. Looks like a path of something was added in the middle of that line.

The entry in question:

https://github.com/OceansAus/1deg_core_nyf/blob/master/ocean/field_table#L118

That is just a very verbose name for the field table entry, I guess to document where that info was coming from on the GFDL servers.

The code that parses `field_table` and sets the `fld_name` for this case is here if you're interested:

https://github.com/mom-ocean/MOM5/blob/43986e20236cc74b83cd5ee09ebd798f4da40824/src/shared/field_manager/field_manager.F90#L687

**Comment by aidanheerdegen** [comment]
Meant to ping @AndyHoggANU and @aekiss into my reply above.

**Comment by aekiss** [comment]
An update: the 1 deg JRA55-do field_table has contained Rayleigh damping for a long time now, for both IAF and RYF:
https://github.com/COSIMA/1deg_jra55_iaf/blob/653ae3d590c7a9c917971269b3a9b4661127e41e/ocean/field_table

However the field_table for 1deg_core_nyf configuration https://github.com/COSIMA/1deg_core_nyf/blob/213a52632e2e60c50c217d18af3cf6f4224aaece/ocean/field_table
is incorrect - it has a lot more Rayleigh damping entries and they are at incorrect indices (none of the j indices exist on the 360x300 1 deg grid). It looks like these values have been pasted in from a higher resolution configuration (probably 0.25deg by the look of it - this is 1440x1080). So presumably none of this damping was actually applied.

For comparison, see https://github.com/COSIMA/access-om2/issues/156

I'll fix this when I make the corrections in https://github.com/COSIMA/access-om2/issues/156

**Comment by aekiss** [comment]
closing - fixed in ak_dev branch and this config is deprecated
